

GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": " Arionpoi",
    "number": "465256765"
}


###
DELETE http://localhost:3001/api/persons/2

###
